CREATE TABLE ODS_PO(
  PO_SERIAL             Number,
  PO_BILL_NUMBER        VARCHAR2(26),
  PO_DATE               Number,
  PO_EMP_ID             Number,
  PO_CUST_ID            Number,
  PO_ITEM_DESC          VARCHAR2(128),
  PO_QUANTITY           Number,
  PO_UNIT_PRICE         Number,
  PO_TOTAL_PRICE        Number,
  EMP_EMP_ID            VARCHAR2(20),
  EMP_FULL_NAME         VARCHAR2(20),
  EMP_FULL_NAME_OL      VARCHAR2(20),
  EMP_HIRE_DATE         DATE
  EMP_EMAIL             VARCHAR2(20),
  EMP_TELEPHONE_NUMBER  VARCHAR2(20),
  CUST_CUST_ID          VARCHAR2(20),
  CUST_FULL_NAME        VARCHAR2(80),
  CUST_FULL_NAME_OL     VARCHAR2(80),
  CUST_CUST_SINCE_DATE  VARCHAR2(20),
  CUST_ADDRESS          VARCHAR2(150),
  CUST_CUST_TYPE        VARCHAR2(20),
  CUST_EMAIL            VARCHAR2(20),
  CUST_TELEPHONE_NUMBER VARCHAR2(20),
);

CREATE TABLE EMP_ORDERS(
  EMP_ID           NUMBER,
  EMP_NAME         VARCHAR2(100),
  EMP_NAME_OL      VARCHAR2(100),
  TOTAL_ORDERS     INTEGER
);

CREATE TABLE CUST_ORDERS(
  CUST_ID           NUMBER,
  CUST_NAME         VARCHAR2(100),
  CUST_NAME_OL      VARCHAR2(100),
  TOTAL_ORDERS     INTEGER
);